version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    container_name: banco-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  backend:
    image: eduardoporto/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: eduardoporto/frontend-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

